repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: double-quote-string-fixer
      - id: fix-byte-order-marker
      - id: check-added-large-files
      - id: check-json
        exclude: ^assets/js/data/search\.json$
      - id: pretty-format-json
        exclude: ^(assets/js/data/search\.json|\.devcontainer/devcontainer\.json|\.vscode/settings\.json)$
      - id: check-toml
      - id: check-xml
        exclude: ^assets/(feed\.xml|img/favicons/browserconfig\.xml)$
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-merge-conflict
